server:
  port: 8090

# 分组任务配置
chatbot-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: ChatGPT AI 问答助手
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
  group02:
    groupName: 码农会锁
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: true


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@//88.8.158.145:28000/XL323_XSYLSJ
    username: APP_XSYLSJ
    password: Xl323@Db2022
    max-idle: 10
    max-wait: 10000

#mybatis-plus:
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/cn/bugstack/chatbot/api/zhijie/xml/*.xml
  #  mapperLocations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.xinluo.sandBox.dto.po
  type-aliases-package: cn.bugstack.chatbot.api.zhijie.entity
    #  global-config:
    #    db-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    # id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #      field-strategy: FieldStrategy.NOT_EMPTY
    #驼峰下划线转换
    #      db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #      refresh-mapper: true
  #数据库大写下划线转换
  #capital-mode: true